Add /.idea/ to .gitignore
darhan1168/Homeworks pull request #3
Opened 2023-03-25 16:13 UTC by darhan1168

2023-03-27 16:58 UTC, vemontd1 requested changes

2023-03-27 16:58 UTC, vemontd1 commented on .gitignore
> +/.idea/
Change to **/.idea/**

2023-03-27 18:26 UTC, darhan1168 commented on .gitignore
> +/.idea/
Fixed

2023-03-30 01:20 UTC, vemontd1 approved these changes

2023-03-30 04:47 UTC, merged